# create a travis env variable to get the first 6 chars of the git commit hash. $TRAVIS_COMMIT has the full hash value.
sudo: required
services:
  - docker
before_install:
  - ./bin/install-k8tools.sh
script:
  - ./bin/test-proj.sh
after_success:
  - ./bin/run-kube.sh
